[bssg]

[build]
step = "steplist"
steps = ["rmdocs", "mkdocs", "cname", "webring", "less", "pugindex"]

[rmdocs]
step = "rm"
path = "docs"

[mkdocs]
step = "mkdir"
path = "docs"

[cname]
step = "cp"
inputFile = "CNAME"
outputFile = "docs/CNAME"

[webring]
step = "cp"
inputFile = "webring.txt"
outputFile = "docs/webring.txt"

[less]
step = "transformless"
inputFile = "style.less"
outputFile = "docs/style.css"

[pugindex]
step = "transformpug"
inputFile = "pug/index.pug"
outputFile = "docs/index.html"
