[bssg]

[[build.steps]]
step = "rm"
path = "docs"

[[build.steps]]
step = "mkdir"
path = "docs"

[[build.steps]]
step = "cp"
inputFile = "CNAME"
outputFile = "docs/CNAME"

[[build.steps]]
step = "cp"
inputFile = "webring.txt"
outputFile = "docs/webring.txt"

[[build.steps]]
step = "transformless"
inputFile = "style.less"
outputFile = "docs/style.css"

[[build.steps]]
step = "transformpug"
inputFile = "pug/index.pug"
outputFile = "docs/index.html"
